name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "$" > "$HOME/.ssh/ida_rsa"
      - run: chmod 600 "$HOME/.ssh/ida_rsa"
      # Build

      # Deploy
      - run: rsync -e "ssh -p 22 -i $HOME/.ssh/ida_rsa -o StrictHostKeyChecking=no" --archive --compress --delete . pasegopf@pasegopf.beget.tech:/home/p/pasegopf/rksf.ru/public_html
